name: 'Cloudflare asset upload action'
description: 'A github action that provides functions which make publishing new assets easier.'
inputs:
  command:
    description: 'The argument to define what this action should do'
    required: true
outputs:
  version:
    description: 'The generated version for your assets'
runs:
  using: 'node20'
  main: 'dist/index.js'